import type { AgentDefinition } from './eventtypes.js';

export const AGENTS: AgentDefinition[] = [
  {
    name: 'WeatherBot',
    domain: 'weather.aldor.sol',
    path: '/api/weather',
    category: 'utility',
    token: 'SOL',
    priceAtomic: 1_000_000,
    recursive: false,
    reputation: 7_500,
    description: 'Real-time weather lookup for any location',
  },
  {
    name: 'Summarizer',
    domain: 'summarizer.aldor.sol',
    path: '/api/summarize',
    category: 'nlp',
    token: 'PALM_USD',
    priceAtomic: 100,
    recursive: false,
    reputation: 8_000,
    description: 'Concise text summarization with key extraction',
  },
  {
    name: 'MathSolver',
    domain: 'math.aldor.sol',
    path: '/api/math-solve',
    category: 'utility',
    token: 'PALM_USD',
    priceAtomic: 300,
    recursive: false,
    reputation: 7_700,
    description: 'Advanced math problem solver with step-by-step reasoning',
  },
  {
    name: 'SentimentAI',
    domain: 'sentiment.aldor.sol',
    path: '/api/sentiment',
    category: 'nlp',
    token: 'PALM_USD',
    priceAtomic: 100,
    recursive: false,
    reputation: 8_200,
    description: 'Sentiment classification and emotional tone analysis',
  },
  {
    name: 'CodeExplainer',
    domain: 'code-explainer.aldor.sol',
    path: '/api/code-explain',
    category: 'code',
    token: 'PALM_USD',
    priceAtomic: 400,
    recursive: false,
    reputation: 8_100,
    description: 'Explain source code in plain English',
  },
  {
    name: 'TranslateBot',
    domain: 'translate.aldor.sol',
    path: '/api/agent/translate',
    category: 'nlp',
    token: 'PALM_USD',
    priceAtomic: 300,
    recursive: false,
    reputation: 7_900,
    description: 'Multi-language text translation',
  },
  {
    name: 'DeepResearch',
    domain: 'research.aldor.sol',
    path: '/api/agent/research',
    category: 'research',
    token: 'PALM_USD',
    priceAtomic: 8_000,
    recursive: false,
    reputation: 8_700,
    description: 'Deep research assistant with comprehensive topic analysis',
  },
  {
    name: 'CodingAgent',
    domain: 'coding.aldor.sol',
    path: '/api/agent/code',
    category: 'code',
    token: 'PALM_USD',
    priceAtomic: 15_000,
    recursive: false,
    reputation: 8_500,
    description: 'Senior coding agent for code generation and review',
  },
  {
    name: 'SovereignSpecialist',
    domain: 'sovereign.aldor.sol',
    path: '/api/agent/sovereign',
    category: 'qvac',
    token: 'PALM_USD',
    priceAtomic: 2_500,
    recursive: false,
    reputation: 8_400,
    description: 'Local-first QVAC specialist for sovereign inference',
  },
  {
    name: 'DataAnalyst',
    domain: 'data.aldor.sol',
    path: '/api/agent/data',
    category: 'analytics',
    token: 'PALM_USD',
    priceAtomic: 800,
    recursive: false,
    reputation: 8_300,
    description: 'Structured data analysis and insight generation',
  },
  {
    name: 'ContractAuditor',
    domain: 'audit.aldor.sol',
    path: '/api/agent/audit',
    category: 'security',
    token: 'PALM_USD',
    priceAtomic: 1_500,
    recursive: false,
    reputation: 8_600,
    description: 'Smart contract security audit and vulnerability detection',
  },
  {
    name: 'DeFiStrategist',
    domain: 'defi.aldor.sol',
    path: '/api/agent/defi',
    category: 'finance',
    token: 'PALM_USD',
    priceAtomic: 1_200,
    recursive: false,
    reputation: 8_200,
    description: 'DeFi yield optimization and strategy recommendations',
  },
  {
    name: 'ImageGenerator',
    domain: 'image.aldor.sol',
    path: '/api/agent/image',
    category: 'creative',
    token: 'PALM_USD',
    priceAtomic: 2_000,
    recursive: false,
    reputation: 7_800,
    description: 'AI image generation from text prompts',
  },
  {
    name: 'MarketOracle',
    domain: 'oracle.aldor.sol',
    path: '/api/agent/oracle',
    category: 'finance',
    token: 'SOL',
    priceAtomic: 5_000_000,
    recursive: false,
    reputation: 8_800,
    description: 'Real-time crypto market data and price feeds',
  },
  {
    name: 'LegalAdvisor',
    domain: 'legal.aldor.sol',
    path: '/api/agent/legal',
    category: 'legal',
    token: 'PALM_USD',
    priceAtomic: 3_000,
    recursive: false,
    reputation: 8_100,
    description: 'Contract review and legal document analysis',
  },
  {
    name: 'SocialMediaBot',
    domain: 'social.aldor.sol',
    path: '/api/agent/social',
    category: 'marketing',
    token: 'PALM_USD',
    priceAtomic: 600,
    recursive: false,
    reputation: 7_600,
    description: 'Social media content generation and scheduling',
  },
  {
    name: 'TradingBot',
    domain: 'trading.aldor.sol',
    path: '/api/agent/trading',
    category: 'finance',
    token: 'PALM_USD',
    priceAtomic: 5_000,
    recursive: true,
    reputation: 8_900,
    description: 'Automated trading signals and execution strategies',
  },
  {
    name: 'MedicalAdvisor',
    domain: 'medical.aldor.sol',
    path: '/api/agent/medical',
    category: 'health',
    token: 'PALM_USD',
    priceAtomic: 1_800,
    recursive: false,
    reputation: 8_000,
    description: 'Medical information retrieval and symptom analysis',
  },
];

export function formatPrice(agent: AgentDefinition): string {
  if (agent.token === 'SOL') {
    return `${agent.priceAtomic / 1_000_000_000} SOL`;
  }
  return `${(agent.priceAtomic / 1_000_000).toFixed(4)} Palm USD`;
}

export function byName(name: string): AgentDefinition | undefined {
  return AGENTS.find((agent) => agent.name === name);
}
